# Generated by Django 4.1.1 on 2022-09-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('BookName', models.CharField(max_length=50)),
                ('BookWriter', models.CharField(max_length=50)),
                ('BookDisc', models.TextField()),
                ('BookStatus', models.CharField(default='AVAILABLE', max_length=50)),
            ],
        ),
    ]
